[workspace]

members = [
    "actixwebgun",
    "datagun",
    "wsgun",
    "httpgunjs",
    "hypergun",
    "rocketgun",
    "rouillegun",
    "tokiogun",
    "tungstenitegun",
    "warpgun",
    "websocketgun"    
]