[package]
name = "warpgun"
version = "0.1.0"
authors = ["Lightnet <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1"
pretty_env_logger = "0.3.1"
warp = "0.1.19"
